from typing import Dict, List
from datamodel import Listing, OrderDepth, Trade, TradingState, ConversionObservation,  Observation, Order
from Michelle_algo_round3 import Trader

#At the start of the first iteration the run method is called with the TradingState generated by the below code:
timestamp = 0



listings = {
	"AMETHYSTS": Listing(
		symbol="AMETHYSTS", 
		product="AMETHYSTS", 
		denomination= "SEASHELLS"
	),
    
	"STARFRUIT": Listing(
		symbol="STARFRUIT", 
		product="STARFRUIT", 
		denomination= "SEASHELLS"
	),
    
    "ORCHIDS": Listing(
		symbol="ORCHIDS", 
		product="ORCHIDS", 
		denomination= "SEASHELLS"
	),
    
    "STRAWBERRIES": Listing(
		symbol="STRAWBERRIES", 
		product="STRAWBERRIES", 
		denomination= "SEASHELLS"
	),
    
    "ROSES": Listing(
		symbol="ROSES", 
		product="ROSES", 
		denomination= "SEASHELLS"
	),
    
    "CHOCOLATE": Listing(
		symbol="CHOCOLATE", 
		product="CHOCOLATE", 
		denomination= "SEASHELLS"
	),
    
    "GIFT_BASKET": Listing(
		symbol="GIFT_BASKET", 
		product="GIFT_BASKET", 
		denomination= "SEASHELLS"
	),
    
    "COCONUT": Listing(
		symbol="COCONUT", 
		product="COCONUT", 
		denomination= "SEASHELLS"
	),
    
    "COCONUT_COUPON": Listing(
		symbol="COCONUT_COUPON", 
		product="COCONUT_COUPON", 
		denomination= "SEASHELLS"
	),

    
}

order_depths = {
	"AMETHYSTS": OrderDepth(
		buy_orders = {9999: 7, 9998: 5},
		sell_orders={10002: -4, 10001: -8}
	),
	"STARFRUIT": OrderDepth(
		buy_orders={5042: 3, 5043: 5},
		sell_orders={5047: -5, 5048: -8}
	),	
    
    "ORCHIDS": OrderDepth(
		buy_orders={5042: 3, 5043: 5},
		sell_orders={5047: -5, 5048: -8}
	),	
    
    "ROSES": OrderDepth(
		buy_orders={5042: 3, 5043: 5},
		sell_orders={5047: -5, 5048: -8}
	),	
    
    "CHOCOLATE": OrderDepth(
		buy_orders={5042: 3, 5043: 5},
		sell_orders={5047: -5, 5048: -8}
	),	
    
    "STRAWBERRIES": OrderDepth(
		buy_orders={5042: 3, 5043: 5},
		sell_orders={5047: -5, 5048: -8}
	),	
    
    "GIFT_BASKET": OrderDepth(
		buy_orders={5042: 3, 5043: 5},
		sell_orders={5047: -5, 5048: -8}
	),	
    
    "COCONUT": OrderDepth(
		buy_orders={5042: 3, 5043: 5},
		sell_orders={5047: -5, 5048: -8}
	),	
    
    "COCONUT_COUPON": OrderDepth(
		buy_orders={5042: 3, 5043: 5},
		sell_orders={5047: -5, 5048: -8}
	),	
}

own_trades = {
	"AMETHYSTS": [],
	"STARFRUIT": [],
    "ORCHIDS": [],
    "ROSES": [],
    "CHOCOLATE": [],
    "STRAWBERRIES": [],
    "GIFT_BASKET": [],
    "COCONUT": [],
    "COCONUT_COUPON": []
}

market_trades = {
	"AMETHYSTS": [
		Trade(
			symbol="AMETHYSTS",
			price=10000,
			quantity=4,
			buyer="",
			seller="",
			timestamp=900
		)
	],
	"STARFRUIT": [],
    "ORCHIDS": [],
    "ROSES": [],
    "CHOCOLATE": [],
    "STRAWBERRIES": [],
    "GIFT_BASKET": [],
    "COCONUT": [],
    "COCONUT_COUPON": []
    
}

position = {
	"AMETHYSTS": 0,
	"STARFRUIT": 0,
    "ORCHIDS": 0,
    "ROSES": 0,
    "CHOCOLATE": 0,
    "STRAWBERRIES": 0,
    "GIFT_BASKET": 0,
    "COCONUT": 0,
    "COCONUT_COUPON": 0
}

observations = {}
traderData = ""

state = TradingState(
	traderData,
	timestamp,
  listings,
	order_depths,
	own_trades,
	market_trades,
	position,
	observations
)

#Based on the above the run method is run
traderdata = Trader()
result,conversions,message= traderdata.run(state) #this returns 3 values
